In [7]:
import numpy as np

# a. Create and print an array from 1 to 10
array1 = np.arange(1, 11)
print("Array from 1 to 10:\n", array1)

# b. Create and print an array from 0.5 to 5 in increments of 0.25
array2 = np.arange(0.5, 5.25, 0.25)
print("Array from 0.5 to 5 in increments of 0.25:\n", array2)


Array from 1 to 10:
 [ 1  2  3  4  5  6  7  8  9 10]
Array from 0.5 to 5 in increments of 0.25:
 [0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


In [5]:
# a. Create and print an array of 10 elements (1D array)
array3 = np.zeros(10)
print("Array of 10 elements (1D):", array3)

# b. Create and print an array of 12 elements of size 4 x 3
array4 = np.zeros((4, 3))
print("Array of size 4 x 3:\n", array4)


Array of 10 elements (1D): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of size 4 x 3:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# a. Create and print an array of 5 elements from 2 to 12
array5 = np.linspace(2, 12, 5)
print("Array of 5 elements from 2 to 12:\n", array5)

# b. Create and print an array of 4 elements from 3 to 9
array6 = np.linspace(3, 9, 4)
print("Array of 4 elements from 3 to 9:\n", array6)


Array of 5 elements from 2 to 12:
 [ 2.   4.5  7.   9.5 12. ]
Array of 4 elements from 3 to 9:
 [3. 5. 7. 9.]


In [15]:
# a. Create and print an array of random numbers of size 2 x 4
random_array1 = np.random.random((2, 4))
print("Random array of size 2 x 4:\n", random_array1)

# b. Create and print an array of random integers between 10 and 20 of size 3 x 3
random_array2 = np.random.randint(10, 20, (3, 3))
print("Random integer array of size 3 x 3:\n", random_array2)

# Note: When using the reshape operation, the total number of elements must remain the same! 
# For example, an array of size 2x4 has 8 elements, which can be reshaped into an 8x1 array.

# Reshape the first random array to 8 x 1
reshaped_array = random_array1.reshape(8)
print("Reshaped array of size 8:\n", reshaped_array)


Random array of size 2 x 4:
 [[0.72106515 0.49893454 0.21164494 0.7050103 ]
 [0.83633261 0.54645334 0.50960928 0.70057019]]
Random integer array of size 3 x 3:
 [[19 18 12]
 [12 14 18]
 [13 19 19]]
Reshaped array of size 8:
 [0.72106515 0.49893454 0.21164494 0.7050103  0.83633261 0.54645334
 0.50960928 0.70057019]


In [19]:
# Using a fixed seed allows for reproducibility. 
# This means that every time you run your code with the same seed, you will get the same random numbers.

# Setting a fixed seed
np.random.seed(42)

# Drawing random numbers again
random_with_seed = np.random.random((2, 4))
print("Random numbers with a fixed seed (2 x 4):\n", random_with_seed)


Random numbers with a fixed seed (2 x 4):
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]]


In [21]:
# a. Receive 5 numbers from the user and add them to a list
numbers = []
for i in range(5):
    num = float(input(f"Enter number {i + 1}: "))
    numbers.append(num)

# b. Convert the list to a numpy array
array_numbers = np.array(numbers)

# c. Print the largest element in the array
print("Largest element:", np.max(array_numbers))

# d. Print the smallest element in the array
print("Smallest element:", np.min(array_numbers))

# e. Print the shape of the array
print("Shape of the array:", array_numbers.shape)

# f. Print the index of the largest element in the array
print("Index of the largest element:", np.argmax(array_numbers))

# g. Print the index of the smallest element in the array
print("Index of the smallest element:", np.argmin(array_numbers))


Enter number 1:  2
Enter number 2:  3
Enter number 3:  5
Enter number 4:  77
Enter number 5:  8


Largest element: 77.0
Smallest element: 2.0
Shape of the array: (5,)
Index of the largest element: 3
Index of the smallest element: 0
